name: devsecops end to end pipline

on:
     workflow_call:
      secrets:
       DOCKERHUB_USER:
        required: true
       DOCKERHUB_TOKEN:
        required: true
jobs:
  
    code:
      uses: ./.github/workflows/code-quality.yml
    secrets:
      uses: ./.github/workflows/secrets-scan.yml
    dependency:
      uses: ./.github/workflows/dependency-scan.yml
    docker:
      uses: ./.github/workflows/docker-lint.yml
    build:
     uses: ./.github/workflows/docker-build-push.yml
     secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    image:
     uses: ./.github/workflows/image-scan.yml
     secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      