name: devsecops end to end pipline

on:
     
  push:
    branches: [main]
jobs:
  
    code-scan:
      uses: ./.github/workflows/code-quality.yml
    secrets-scan:
      uses: ./.github/workflows/secrets-scan.yml
    dependency-scan:
      uses: ./.github/workflows/dependency-scan.yml
    docker-scan:
      uses: ./.github/workflows/docker-lint.yml
    build-scan:
     needs: [code-scan,secrets-scan,dependency-scan,docker-scan]
     uses: ./.github/workflows/docker-build-push.yml
     secrets: inherit 

    image-scan:
     needs: [build-scan]
     uses: ./.github/workflows/image-scan.yml
     secrets: inherit

    deploy:
     needs: [image-scan]
     uses: ./.github/workflows/deploy-server.yml
     secrets: inherit